### ISSUE TITLE
Bomb plant wrong site

### ISSUE THREAD

**Issue by 3GaNwO** [Technoblazed/sm-autoplant#1]
There is a glitch with your plugin where sometimes the bomb plants on the wrong site. I've only seen it happen a few times. I mentioned this on AM forums but I figured here is where I should actually make the issue post. Hopefully you can figure out why it does this sometimes. I think this is a brilliant plugin and hopefully you can work out this glitch (:

**Comment by 3GaNwO** [comment]
https://i.imgur.com/tR0YRjg.jpg

As you can see here the bomb got planted on plat where the awp is pointing

**Comment by 3GaNwO** [comment]
Here is another screen shot of the bomb being planted t spawn now randomly 

https://imgur.com/gallery/tUPDj

Hopefully this is an easy fix for you

**Comment by 3GaNwO** [comment]
So I think I know what the issue is. I've noticed when you come from spectate back into a retake and you get the bomb that next round the auto planter breaks. It gives users 10 seconds to move around freely before the bomb is planted and can be planted anywhere the bomb planter happens to be after that 10 seconds. Hopefully this helps

**Comment by Technoblazed** [comment]
I can't replicate this, what's your value of mp_freezetime?

**Comment by 3GaNwO** [comment]
I have that that set to 8 right when default value is 12 for splewis do you think if i set that back to default it could fix it?

**Comment by Technoblazed** [comment]
Shouldn’t matter but I’ll give it a check. If not I might know what the issue is.

**Comment by 3GaNwO** [comment]
Hopefully you can figure it out (: I love this plugin and it only happens a couple times in a day. I've noticed that sometimes it basically skips your freeze time and it goes to 12 or 13 seconds of regular moving time (no freezetime at all) then after that 12 or 13 seconds it just plants the bomb where the planter might be its an interesting issue lol

**Comment by Technoblazed** [comment]
No matter what I try, I can't replicate this issue.

**Comment by 3GaNwO** [comment]
Weird yea I still have it from time to time thank you for trying to figure it out I'll let the guys know you couldn't figure out how to replicate the issue to fix it.

**Comment by 3GaNwO** [comment]
I have figured it out! what is happening is when the bomb planter goes afk, gets switched to spectate(from afk manager), with it basically being an empty server when he comes back, and he is the bomb planter when he comes back out of spectate he gets 4 seconds to run anywhere from that spawn and upon 4 seconds it drops the bomb. I hope this helps with replicating that issue

**Comment by Technoblazed** [comment]
Sounds more like a server configuration issue rather than my plugin

**Comment by 3GaNwO** [comment]
hmmm so you think maybe its an afk manager cfg thats causing this issue then? cause I dont think it could be replicated unless the bomber gets switched to spectate and comes back being the bomber again

**Comment by Technoblazed** [comment]
@3GaNwO see if that fixes it

**Comment by 3GaNwO** [comment]
Thank you I will check right now

**Comment by 3GaNwO** [comment]
That fixed it! now when this happens it just appears about a foot off the floor but at least its in the correct bomb location! Thank you Techno! (:
