### ISSUE TITLE
T side bomb Indicator

### ISSUE THREAD

**Issue by 3GaNwO** [Technoblazed/sm-autoplant#2]
This is an enhancement I would like to see with this plugin. Sometimes we don't have the best of players in our server and those players don't check the mini map to see where the bomb is. What I'm wondering is if you can add an indicator during the freeze time that the T's can see so they know where the bomb is being planted at the start of the round and position themselves accordingly!

Great plugin btw thank you for taking the time to code this and make it a public plugin (:

**Comment by Technoblazed** [comment]
Not quite sure of the best way to make this work.

**Comment by Technoblazed** [comment]
On the basis this would be pretty dumb to implement, just use your map and see where they are. Closing this request.
