### ISSUE TITLE
To force the player to bend

### ISSUE THREAD

**Issue by alphaearth** [Technoblazed/sm-autoplant#6]
When the round head is set up automatically, the player needs to bend. But the player can install the standing bomb. If the bomb is standing up, the bomb is set in the air. Would you fix that? Prevent the player from standing up and force him to bend.

**Comment by Technoblazed** [comment]
Thats an issue with your bomb spawn points, the bomb spawns at the feet of the user by default.

**Comment by alphaearth** [comment]
bombs are sometimes installed in the air.

**Comment by Technoblazed** [comment]
You're welcome to create a pr, not really got the time atm.
