### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Had3s99** [Technoblazed/sm-autoplant#7]
Hello,

On my retake server, sometimes the bomb isn't auto plant and the guy need to plant manually, i've no log errors about that but can u check it please ?

Thanks.

**Comment by Had3s99** [comment]
[SM] Listing 58 plugins:
  01 "Rock The Vote" (1.8.0.6041) by AlliedModders LLC
  02 "Admin File Reader" (1.9.0.6266) by AlliedModders LLC
  03 "Anti-Flood" (1.9.0.6266) by AlliedModders LLC
  04 "RandomCycle" (1.9.0.6241) by AlliedModders LLC
  05 "Map Nominations" (1.8.0.6041) by AlliedModders LLC
  06 "Fun Commands" (1.9.0.6266) by AlliedModders LLC
  07 "Simple Stealth" (1.0) by Potatoz
  08 "CallAdmin" (0.1.6) by Impact, dordnung
  09 "CSGO: Timer" (1.0) by Had3s99
  10 "CS:GO Retakes" (0.3.2) by splewis
  11 "Admin Facile" (1.3b) by Steven
  12 "GeoIP Language Selection" (1.3.0) by GoD-Tony
  13 "Casier de tes morts" (1.0) by Had3s99
  14 "CSGO: DemoID" (3.0) by Shytoos
  15 "Client Preferences" (1.9.0.6266) by AlliedModders LLC
  16 "Admin Menu" (1.9.0.6266) by AlliedModders LLC
  17 "Discord API" (1.0) by .#Zipcore, Credits: Shavit, bara, ImACow and Phire
  18 "Player Commands" (1.9.0.6266) by AlliedModders LLC
  19 "Insta-Defuse" (1.2) by Jacoblairm
  20 "Reserved Slots" (1.9.0.6266) by AlliedModders LLC
  21 "Basic Info Triggers" (1.9.0.6266) by AlliedModders LLC
  22 "DR.API HIGH PING KICKER" (1.0.1) by Dr. Api
  23 "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team
  24 "Retake - Bombsite overlays" (1.1) by shanapu
  25 "CallAdmin UserManager" (0.1.6) by dordnung, Impact
  26 "Advanced Admin ESP" (1.3.6) by Mitch
  27 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
  28 "Basic Comm Control" (1.9.0.6266) by AlliedModders LLC
  29 "CS:GO Retakes: Customised Weapon Allocator for splewis retakes plugin" (0.3.2) by BatMen
  30 "CowAntiCheat" (1.16) by CodingCow
  31 "[ANY] Ban Disconnected Player" (2.0) by Headline, Original Plugin : mad_hamster
  32 "Fun Votes" (1.9.0.6266) by AlliedModders LLC
  33 "SourceBans++: Main Plugin" (1.6.2) by SourceBans Development Team, SourceBans++ Dev Team
  34 "CSGO TeamKillManager" (0.1.3) by Zach Perkitny
  35 "Basic Votes" (1.9.0.6266) by AlliedModders LLC
  36 "sbp.smx"
  37 "Basic Commands" (1.9.0.6266) by AlliedModders LLC
  38 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
  39 "CallAdmin: Mysql module" (0.1.5) by Impact, Popoklopsi
  40 "Nextmap" (1.9.0.6266) by AlliedModders LLC
  41 "Basic Chat" (1.9.0.6266) by AlliedModders LLC
  42 "Gloves" (1.0.3) by kgns | oyunhost.net
  43 "Admin Help" (1.9.0.6266) by AlliedModders LLC
  44 "Round Message" (1.0) by LenHard
  45 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
  46 "Weapons & Knives" (1.3.2) by kgns | oyunhost.net
  47 "[CS:GO] Fake Competitive Ranks/Coins" (1.2) by Laam4
  48 "Move Commands ( ResetScore, Switch, Spec )" (2.0.1) by Bara
  49 "DR.API AFK MANAGER" (1.0.1) by Dr. Api
  50 "MapChooser" (1.8.0.6041) by AlliedModders LLC
  51 "Sound Commands" (1.9.0.6266) by AlliedModders LLC
  52 "CS:GO Retakes: site picker" (0.3.2) by splewis
  53 "Admin Smite" (2.1) by Hipster
  54 "Give Weapon" (1.0) by Kiske
  55 "SourceBans++: SourceComms" (1.6.2) by Alex, SourceBans++ Dev Team
  56 "Discord: CallAdmin" (1.1) by .#Zipcore
  57 "CallAdmin: Ts3 module" (0.1.6) by Impact, dordnung
  58 "CSGO: Retake" (1.0) by Had3s99

My plugins

**Comment by Technoblazed** [comment]
Why are you using multiple retakes plugins?

**Comment by Had3s99** [comment]
10 "CS:GO Retakes" (0.3.2) by splewis
24 "Retake - Bombsite overlays" (1.1) by shanapu
29 "CS:GO Retakes: Customised Weapon Allocator for splewis retakes plugin" (0.3.2) by BatMen
52 "CS:GO Retakes: site picker" (0.3.2) by splewis
58 "CSGO: Retake" (1.0) by Had3s99

10- Core plugin
24- For image site
29- I've forget lol
52- Forget toi
58- My script for chat color, clan tag, vip advantage etc..

**Comment by b3none** [comment]
You're using an older version of Retakes. Please update it. I'd also recommend using my version _cough_ [this one](https://github.com/b3none/retakes-autoplant) _cough_

If you're still struggling with this after the switch drop me a message on Discord and I'll talk you through it.

Discord: B3none#0575

**Comment by Had3s99** [comment]
Okay i'll update and give feedback before the end of the week :)

**Comment by Had3s99** [comment]
So well it's fixed now thanks
